name: divine_mercy_app_the_right_way
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.2.1
  firebase_core: ^2.0.0
  firebase_auth: ^4.0.0
  get: ^4.6.5
  shared_preferences: ^2.0.11 
  email_validator: '^2.1.16'
  flutter_svg: ^1.1.5
  cloud_firestore: ^4.0.1
  smooth_page_indicator: ^1.0.0+2
  animated_text_kit: ^4.2.2
  pin_input_text_field: ^4.2.0
  loading_overlay: ^0.3.0
  flutter_spinkit: ^5.1.0
  country_code_picker: ^2.0.2
  permission_handler: ^10.2.0
  image_picker: ^0.8.6
  image_cropper: ^3.0.0
  firebase_storage: ^11.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - asset/images/
    - assets/images/
    - assets/icons/
    - assets/audio/

  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Meduim.ttf
          weight:  500
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight:  600
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight:  700



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  